name: AdvancedKits
main: AdvancedKits\Main
version: 5.2.3
api: [3.0.0]
author: luca28pet
softdepend: [PurePerms, PiggyCustomEnchants, FormAPI]
commands:
 kit:
  description:
  usage: "/kit <kitName>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
 akreload:
  descrpition:
  usage: "/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: ""
  default: true
 advancedkits.admin:
  description: ""
  default: op
